---
- version: '3.8'
  services:
   mydb: 
    image: mysql:5
    environment:
     - MYSQL_ROOT_PASSWORD: dillip
   mywordpress:
    image: wordpress
    ports:
     - 9999:80
    links:
     - mydb:mysql
